### ISSUE TITLE
Vagrant cURL scp support on Mac OS X

### ISSUE THREAD

**Issue by mmorel10** [mitchellh/vagrant-installers#30] opened 2013-11-20 02:47 UTC
I would like to use Vagrant to download a box via scp on Mac OS X.

Per this pull request, I thought the feature would be built in:
https://github.com/mitchellh/vagrant/pull/1041

Unfortunately, the embedded cURL within the Vagrant package does not support scp.  I believe this can be resolved by building libssh2, and adding it as a dependency to cURL.

**Comment by gsaslis** [comment] 2015-02-26 06:47
on OSX, i think the problem is the fact that libcurl ships without support for scp built-in. You can easily tell by running 
```
curl --version
```
which should display a list of the supported protocols. On OSX 10.10 (at least), scp is not on that list. 

The solution is to install a second version of curl - I originally found it on here: 
http://chase-seibert.github.io/blog/2014/05/18/vagrant-authenticated-private-box-urls.html

Hope this helps...

**Comment by ccope** [comment] 2015-07-01 00:58
The linux builds are also lacking scp/sftp support in curl. I think that curl needs to link against libssh2?

**Comment by sethvargo** [comment] 2015-07-09 19:41
Hi there,

Thank you for opening an issue. We now ship our own embedded curl, even on OSX.

**Comment by ccope** [comment] 2015-07-10 00:09
@sethvargo The embedded curl isn't built against libssh2, so it doesn't have scp/sftp support.

**Comment by chrisroberts** [comment] 2017-06-21 15:24
Hi there,

It looks like this has been resolved within a previous update so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Closed by chrisroberts** 2017-06-21 15:24 UTC
